Note_Book/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings             
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('note_book/',include("Note_Book_app.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Note_Book_app/urls.py
from django.urls import path,include
from . import views


app_name="Note_Book_app"

urlpatterns = [
    path("",views.main_page_view.as_view(),name='main_page'),
    path("new_note",views.new_note_view.as_view(),name='new_note'),
    path("previous_notes",views.previous_notes_view.as_view(),name='previous_notes'),
    path("note/<int:pk>",views.note_view.as_view(),name='note_detail_page'),
    path("edit_note/<int:pk>",views.edit_note_view.as_view(),name='edit_note'),
    path("delete_note/<int:pk>",views.delete_note_view.as_view(),name='delete_note'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('edit_profile/', views.edit_ProfileView.as_view(), name='edit_profile'),
]

Note_Book_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User




# Create your models here.

class Note(models.Model):
    """
    this function is the Note model of the Note_Book_app of the Note_Book django project.
    in front of each field and each function you can see it's discription.
    """
    name=models.CharField(blank=True) # this is the name field of the model.
    note=models.TextField(verbose_name="write your note here.") #this is the note field of the model.
    Published_at=models.DateTimeField(auto_now_add=True) #this is published_at field of the model that saves the time whenever note is published.
    Update_at=models.DateTimeField(auto_now=True) #this is Upadted_at field of the model that stores the time when the object is updated.
    user=models.ForeignKey(User, on_delete=models.CASCADE,null=True,blank=True)

    def __str__(self): # shows the name field of the note.
        return self.name
    
    def get_absolute_url(self): #Returns the canonical URL for a single note instance.
        return reverse("Note_Book_app:note_detail_page", kwargs={'pk': self.pk})
    

    def save(self,*args, **kwargs): #this function auto generate field name from pk if field name is null.
        super().save(*args, **kwargs)

        if not self.name:
            self.name = f"note {self.pk}"
            super().save(update_fields=['name'])


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    profile_picture = models.ImageField(upload_to='profile_pics/', default='default.jpg')

    def __str__(self):
        return f'{self.user.username} Profile'
    

Note_Book_app/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from .models import Note,Profile
from django.views.generic import ListView,DetailView
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.

#this class is for the first page that you face.the url is ./note_book
class main_page_view(LoginRequiredMixin,TemplateView):
    template_name = "main_page.html"

#this class is for the new note page that contains a form.
class new_note_view(LoginRequiredMixin,CreateView):
    template_name = "new_note.html"
    model = Note
    fields = ["name","note"]

    def form_valid(self, form):
        form.instance.user=self.request.user
        return super().form_valid(form)
    
    def get_queryset(self):
        return Note.objects.filter(user=self.request.user)

#this is for the previous_note page that contains links to saved notes.
class previous_notes_view(LoginRequiredMixin,ListView):
    template_name="previous_notes.html"
    model= Note
    paginate_by=10
    ordering=['-Published_at']

    def get_queryset(self):
        return Note.objects.filter(user=self.request.user)

#this function shows the detail of a created view.
class note_view(LoginRequiredMixin,DetailView):
    model=Note
    template_name='note_detail.html'
    context_object_name = 'note'

    def get_queryset(self):
        return Note.objects.filter(user=self.request.user)


#This function edit notes.
class edit_note_view(LoginRequiredMixin,UpdateView):
    model=Note
    template_name='new_note.html'
    fields=["name","note"]
    def post(self, request, *args, **kwargs):
        self.object=self.get_object()
        response=super().post(request, *args, **kwargs)
        messages.success(request,f"the {self.object} was successfully edited!")
        return response
    
    def get_queryset(self):
        return Note.objects.filter(user=self.request.user)

#this function delete notes.
class delete_note_view(LoginRequiredMixin,DeleteView):
    model = Note
    template_name='delete_note_confirmation.html'
    success_url = reverse_lazy("Note_Book_app:previous_notes")
    def post(self, request, *args, **kwargs):
        self.object=self.get_object()
        response=super().post(request, *args, **kwargs)
        messages.success(request,f"the {self.object} was successfully deleted!")
        return response
    
    def get_queryset(self):
        return Note.objects.filter(user=self.request.user)


class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login') 
    template_name = 'registration/signup.html'


class ProfileView(LoginRequiredMixin,DetailView):
    model=Profile
    template_name='profile.html'
    context_object_name = 'profile'

    def get_object(self, queryset=None):
        return self.request.user.profile
    

class edit_ProfileView(LoginRequiredMixin,UpdateView):
    model=Profile
    template_name='edit_profile.html'
    fields = ['bio','profile_picture']
    success_url = reverse_lazy("Note_Book_app:profile")

    def get_object(self, queryset=None):
        return self.request.user.profile

    

Note_Book_app/templates/delete_note_confirmation.html
<form method="post">{% csrf_token %}
    



<p>Are you sure you want to delete "{{ object }}"?</p>




    <input type="submit" value="Confirm">
</form>

Note_Book_app/templates/edit_profile.html
<div class="container mt-4">
    <h2>ویرایش پروفایل</h2>
    <hr>

    <form method="post" enctype="multipart/form-data">

        {% csrf_token %}

        {{ form.as_p }}

        <br>
        <button type="submit" class="btn btn-primary">ذخیره تغییرات</button>
    </form>
</div>

Note_Book_app/templates/main_page.html
<!DOCTYPE html>
<html>
<body>

<h1>Note book app</h1>
  
<a href="{% url 'Note_Book_app:new_note' %}">New_note</a></p>
<a href="{% url 'Note_Book_app:previous_notes' %}">Previous Notes</a></p>


{% if user.is_authenticated %}
    <span>سلام، {{ user.username }}!</span>
    
    <form action="{% url 'logout' %}" method="post" style="display: inline;">
        {% csrf_token %}
        <button type="submit">logout</button>
    </form>

{% else %}
    <a href="{% url 'login' %}">login</a>
    {% comment %} <a href="{% url 'signup' %}">signup</a> {% endcomment %}
{% endif %}

Note_Book_app/templates/new_note.html
    {%if object%}
    <form action="{% url 'Note_Book_app:edit_note' object.pk %}" method="post">
{% else %}
    <form action="{% url 'Note_Book_app:new_note' %}" method="post">
{%endif%}
        {% csrf_token %}
        
        {{ form.as_p }}
        
        <button type="submit">Save</button>
    </form>
{{object.note}}

<a href="{% url 'Note_Book_app:previous_notes' %}">Previous Notes</a></p>

Note_Book_app/templates/note_detail.html
<h1>note title: {{ note.name }}</h1>
<p>note context: {{ note.note }}</p>
<p>publish time: {{ note.Published_at }}</p>
<p>id of the note: {{ note.id }}</p>
<p>Update time: {{ note.Update_at }}</p>


<h3><a href="{% url 'Note_Book_app:new_note' %}">add a new note</a></h3>
<h3><a href="{% url 'Note_Book_app:previous_notes' %}">previous notes page</a></h3>
<h3><a href="{% url 'Note_Book_app:edit_note' pk=note.id %}">edit note</a></h3> 
<h3><a href="{% url 'Note_Book_app:delete_note' pk=note.id %}">delete_note</a></h3> 

Note_Book_app/templates/pervious_note.html
TEST

Note_Book_app/templates/pervious_notes.html
TEST

Note_Book_app/templates/previous_notes.html
{% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li>{% if message.tags %} {{ message.tags }}{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}


<ul> 

    {% for object in object_list %} 

<li><a href="{% url 'Note_Book_app:note_detail_page' pk=object.id %}">{{ object.name }}</a></li>  
  
    <hr/> 
    {% empty %} 
    <li>No notes yet.</li> 
    {% endfor %} 
</ul>


<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

<h1><a href="{% url 'Note_Book_app:new_note' %}">add a new note</a></h1>

Note_Book_app/templates/profile.html
{% if user.is_authenticated %}
  <span>سلام، {{ user.username }}!</span> |
  <ul>
<li>  <a href="{% url 'Note_Book_app:profile' %}">پروفایل من</a></li> |
  
<li> <a href="{% url 'password_change' %}">تغییر رمز عبور</a></li> |
  
<li>    <a href="{% url 'Note_Book_app:edit_profile' %}">edit profile</a></li> |

<li>         bio:{{profile.bio}}</li>

<li>    <img src="{{ profile.profile_picture.url }}" alt="عکس پروفایل" width="500"></li>


  </ul>
  
  <form action="{% url 'logout' %}" method="post" style="display: inline;">
    {% csrf_token %}
    <button type="submit">خروج</button>
  </form>
{% else %}
  <a href="{% url 'login' %}">ورود</a>
{% endif %}